### ISSUE TITLE
Hardcoded Graphviz path for Windows

### ISSUE THREAD

**Issue by jermeyyy** [nvinayshetty/StateArts#1]
Currently path for graphviz executable is hardcoded for specific version, making it hard to use for Windows users (hardcoded version is already outdated). How about using graphviz by using system PATH? Only downside is forcing users to add graphviz executable path to system PATH. Anyway, great work.

**Comment by nvinayshetty** [comment]
Thanks @jermeyyy , Yes currently this is handled badly for windows users! In fact this plugin is never tested on windows! mainly becuase I don't have access to a windows machine!  As a temporary fix, I will update the graphviz version soon, but that will not survive for long! If you don't mind are you okay with creating PR with your proposed changes? I will be happy to assist you.

**Comment by nvinayshetty** [comment]
@jermeyyy The version fix is now live could you please help me verify that it works in windows?
